# Numpy - the effective way for computation
## TOPICS:

1. What is NumPy?
    * 1.1 NumPy Arrays
        * 1-d array
        * 2-d array  
2. Installing NumPy
3. CRUD
    * 3.1 CREATE
    * 3.2 READ
    * 3.3 UPDATE
    * 3.4 DELETE
4. Some useful functions
5. Operations with matrices

## 1. What is NumPy?
>NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more. - NumPy.org

The key characteristics of NumPy:
* NumPy arrays have a fixed size (unlike list Python that you can append)
* All elements must be the same type ( cannot mix type like list in Python)

**It sounds very limited, what should we use it?**

Answer: **It is fast!** In data science we have to deal with a lot of data points. If the underlying data structures are slow, it will significantly affect the performance.

**How will we use NumPy in this course?**

We will use NumPy arrays:

* Vector : 1-d array
* Matric : 2-d array

## 2. Installing NumPy
Open (go back to) Anaconda Navigator, select the environment that you want to use. If you never create any new environment, select **base(root)**. You will see a list of installed packages. Change that to **All**. Now, type **numpy** into the search box. We should see something like this:

![InstallNumPy1](assets/InstallNumPy1.png)

Click **numpy** , in this case, the version is 1.9.3. Click **Apply**.
![InstallNumPy2](assets/InstallNumPy2.png)

Now, we will see the details. What packages will be installed. Click **Apply** and then wait a little while..
![InstallNumPy3](assets/InstallNumPy3.png)


## 1.1 NumPy Arrays
To create NumPy Arrays, we need to import it first

_Note: It is a convention to give a shorter name to the library. Here, we use **np** as the nickname of it._

In [1]:
import numpy as np

### 1-d array
Now, we can create a NumPy array. We can by using data from a list.

In [2]:
my_list = [11,13,15]
np.array(my_list)

array([11, 13, 15])

We just create a 1-d array (vector). Let's assign that to a variable. We can get the dimension of our array by calling **.shape** and then we will get a tuple where the elements are the dimentions.

In [3]:
my_list = [11,13,15]
x = np.array(my_list)
x.shape

(3,)

**We can access the element by using an index.**  Note: Index start at 0.

In [4]:
x[1]

13

Using 3rd libralies bring new data structures into Python. It is a good idea to see what data structure we are using. We can call **type(varible)** to see the data type.

In [5]:
type(x)

numpy.ndarray

Note, type of the N-dimensional array is **ndarray**.
The ndarray has a property **shape** that holds the tuple. Length of the tuple indicates **N**, the dimension of the array.

Since we just make a 1-d array, length of the tuple is 1.

In [6]:
type(x.shape) # this shall be a tuple
len(x.shape) # this will show length of the tuple

1

A quick reminder about tuple.


In [ ]:
a = (3,4)
type(a) # this shall be a tuple
len(a) # this shall be 2

### 2-d array
In the same manner with creating a 1-d array in NumPy, we can create a 2-d array by using data from a list.

First, we create a list of lists.

```my_2d_list = [ ? , ? , ? ]```

Each ? is also a list.


In [9]:
my_2d_list = [ [1,2] , [3,4] , [5,6] ]

Now, we can create an array.

In [10]:
y = np.array(my_2d_list)

We can access using index.

In [11]:
y[2,1]

6

### Practice Time ###

**Challenge #1**
Creat a 2-d array with data as shown.
Assign the created array to a variable z
![matric](assets/2DMatric.png)

In [16]:
my_2d_list = [ [10,20,30,40] , [50,60,70,80] , [90,100,110,120]  ]
z = np.array(my_2d_list)
z

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [17]:
z[1,3]

80

**Challenge #2**
Creat a 3-d array with data as shown.
Assign the created array to a variable m
![matric](assets/3DMatric.png)

In [20]:
my_3d_list = [[[1,10,100],[2,20,200],[3,30,300]],[[4,40,400],[5,50,500],[6,60,600]] ]
m = np.array(my_3d_list)
m

array([[[  1,  10, 100],
        [  2,  20, 200],
        [  3,  30, 300]],

       [[  4,  40, 400],
        [  5,  50, 500],
        [  6,  60, 600]]])

In [21]:
m[1,1,2]

500

## 3. CRUD
### 3.1 CREATE
We can create a NumPy array from a list.

In [ ]:
my_2d_list = [ [1,2] , [3,4] , [5,6] ]
my_np_arr = np.array(my_2d_list)
my_np_arr

### 3.2 READ
We can access the element by using indexes. With the same manner as Python, the index starts from 0.

In [ ]:
my_np_arr[2,1] # [ROW,COL]

### 3.3 UPDATE
1. Change value
2. Append data (returning a new array)

We can change value by reassigning the new value to the array.

In [ ]:
my_np_arr[2,1] = 555
my_np_arr

We can append two arrays together. It will flatten to 1d, join them, and return a **new** array.

In [22]:
arr1 = np.array( [ [1,2] , [3,4] , [5,6] ] )
arr2 = np.array( [[7,8]])
arr3 = np.append(arr1,arr2) # It returns a new array. It doesn't add arr2 to arr1.
arr3

array([1, 2, 3, 4, 5, 6, 7, 8])

Notice that the dimension is not 4 rows 2 columns. We have to reshape this 1-d array to the desired dimension.

In [23]:
print(arr3.shape) # Will get (8,)
arr4 = arr3.reshape(4,2) # It doesn't change arr3, but use data to make a new array
print(arr3)
print('---')
print(arr4)

(8,)
[1 2 3 4 5 6 7 8]
---
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### 3.4 DELETE
We cannnot delete existing element. NumPy makes a new array without the deleted item.

```python
np.delete( array, index, axis )
```
axis 0 is along rows, axis 1 is along the columns

In [26]:
arr1 = np.array( [ [1,2] , [3,4] , [5,6] , [7,8]] ) 
# We want to delete the row that has [5,6]. It is row 2. Axis 0
arr2 = np.delete(arr1,2,0)
arr2

array([[1, 2],
       [3, 4],
       [7, 8]])

In [25]:
arr1 = np.array( [ [1,2] , [3,4] , [5,6] , [7,8]] ) 
# Now,let's try to delete column that has 2 4 6 8
# That's index 1, axis 1
arr3 = np.delete(arr1,1,1)
arr3

array([[1],
       [3],
       [5],
       [7]])

Keep in mind that NumPy arrays don't change. When we modify it, the modified one is the **NEW ARRAY**.

In [24]:
print(arr1)
print('---')
print(arr3)

[[1 2]
 [3 4]
 [5 6]]
---
[1 2 3 4 5 6 7 8]


## 4. Some useful functions

Create array with elements from START(default is 0) to STOP (exclusive). You can also specify step size.

In [28]:
arr11 = np.arange(0,10) 
arr11

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr12 = np.arange(0,10,4)
arr12

array([0, 4, 8])

In [29]:
arr13 = np.zeros(3)
arr13

array([0., 0., 0.])

In [30]:
arr14 = np.zeros((2,3))
arr14

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
arr15 = np.ones((4,5))
arr15

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
arr16 = np.identity(3)
arr16

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
arr17 = np.eye(5)
arr17

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
arr18 = np.eye(5,k=1)
arr18

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [33]:
arr19 = np.random.rand(3,2)
arr19

array([[0.53443967, 0.32136812],
       [0.45407471, 0.57769355],
       [0.88180824, 0.55178093]])

In [36]:
p = np.random.randint(0,100,30)
p

array([17, 94, 66, 15,  1, 99, 19, 26, 97,  4, 25, 48, 38, 10, 81, 57, 96,
       79, 45, 55, 83, 75, 25, 17, 79, 71, 54, 76, 80, 64])

In [37]:
new_array = p.reshape(5,6)
new_array

array([[17, 94, 66, 15,  1, 99],
       [19, 26, 97,  4, 25, 48],
       [38, 10, 81, 57, 96, 79],
       [45, 55, 83, 75, 25, 17],
       [79, 71, 54, 76, 80, 64]])

In [38]:
p.min()

1

In [39]:
p.argmin()

4

In [40]:
p.max()

99

In [41]:
p.argmax()

5

## 5. Operations with matrices

### ADD
If you remember, when we have two lists and we add them together.
What would be the result?


In [42]:
a = [1,3,5]
b = [20, 30, 40]
c = a + b
c

[1, 3, 5, 20, 30, 40]

With NumPy, let's try to **ADD** them again.

In [43]:
d = np.array( [1,2,3])
e = np.array( [10,100,1000])
d + e

array([  11,  102, 1003])

**If the dimensions are not the same, you will get an error message.**


In [44]:
d = np.array( [1,2,3,4])
e = np.array( [10,100,1000])
d + e

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

** What if we want to append an array to another array?**
You cannot add data to an existing array. However, you can copy elements and append a new one to form a new array. This can be slow if you have a lot of data points.

In [45]:
f = np.array(["ha","ho"])
g = np.array(["hey","how"])
h = np.append(f,g)
h

array(['ha', 'ho', 'hey', 'how'], dtype='<U3')

### MULTIPLY
We can multiply a matric with a scalar.

Try:
```python
g = np.array( [1,2,3] )
2*g
```

In [46]:
g = np.array( [1,2,3] )
2*g

array([2, 4, 6])

In [47]:
i = np.array( [2,3,4])
i*i

array([ 4,  9, 16])